#Minecraft server properties
#Fri Sep 04 01:24:13 CST 2026
view-distance=8
max-build-height=256
server-ip=
level-seed=
server-port=25565
allow-nether=true
enable-command-block=true
gamemode=0
enable-rcon=false
enable-query=false
op-permission-level=2
generator-settings=
resource-pack=
level-name=world
player-idle-timeout=0
motd=GT\:New Horizons 2.9.0-beta-1
pause-when-empty-seconds=0
announce-player-achievements=true
force-gamemode=false
hardcore=false
white-list=false
texture-pack=
pvp=true
spawn-npcs=true
spawn-animals=true
generate-structures=true
snooper-enabled=true
difficulty=3
level-type=rwg
spawn-monsters=true
max-tick-time=-1
max-players=20
spawn-protection=1
online-mode=true
allow-flight=true
